# Read only the first 657 lines (CSS + navigation + hero)
with open('/Users/qweqwe/Desktop/project/index.html', 'r', encoding='utf-8') as f:
    all_lines = f.readlines()

header_lines = all_lines[:657]

# New sections with proper formatting
new_content = [
    '\n',
    '    <!-- 汉语桥 -->\n',
    '    <section id="hanyuqiao">\n',
    '        <h2>汉语桥</h2>\n',
    '        <p class="section-intro">中外语言文化交流的桥梁，让语言成为连接心灵的纽带</p>\n',
    '        \n',
    '        <div class="culture-grid">\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">📚</div>\n',
    '                <h4>汉语课程</h4>\n',
    '                <p>系统化的汉语教学课程体系，从零基础到高级商务汉语，覆盖全年龄段学习者。线上+线下灵活学习模式。</p>\n',
    '            </div>\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">🎉</div>\n',
    '                <h4>语言活动</h4>\n',
    '                <p>定期举办汉语角、演讲比赛、诗词朗诵等活动，营造沉浸式语言学习环境。每月两次，欢迎参与。</p>\n',
    '            </div>\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">🌏</div>\n',
    '                <h4>中外交流项目</h4>\n',
    '                <p>搭建中外青年交流平台，促进文化对话与友谊。留学生配对、文化体验日、语言交换计划等。</p>\n',
    '            </div>\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">📱</div>\n',
    '                <h4>语言学习资源</h4>\n',
    '                <p>在线学习平台提供视频教程、练习题、文化小知识。随时学习，反复巩固，让进步看得见。</p>\n',
    '            </div>\n',
    '        </div>\n',
    '    </section>\n',
    '\n',
    '    <!-- 故事里 -->\n',
    '    <section id="gushi">\n',
    '        <h2>故事里</h2>\n',
    '        <p class="section-intro">用故事讲中国、讲侨情，让文化在讲述中传承</p>\n',
    '        \n',
    '        <div class="culture-grid">\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">📖</div>\n',
    '                <h4>中国故事</h4>\n',
    '                <p>从神话传说到历史典故，用生动的方式讲述中国五千年文明中的经典故事。每周五晚更新，欢迎收听。</p>\n',
    '            </div>\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">👨‍👩‍👧‍👦</div>\n',
    '                <h4>侨胞故事</h4>\n',
    '                <p>记录东南亚侨胞的奋斗历程与思乡情怀，传承爱国爱乡、艰苦创业的精神血脉。来自真实侨胞口述。</p>\n',
    '            </div>\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">🎭</div>\n',
    '                <h4>文化故事</h4>\n',
    '                <p>通过戏曲、舞蹈、节日习俗等载体，讲述文化背后的深层含义与传承价值。每月一个主题故事。</p>\n',
    '            </div>\n',
    '            <div class="culture-card">\n',
    '                <div class="icon">🎬</div>\n',
    '                <h4>图文/视频故事</h4>\n',
    '                <p>以多媒体形式呈现精彩内容，图文并茂、视频生动。让故事跨越语言障碍，传递文化温度。</p>\n',
    '            </div>\n',
    '        </div>\n',
    '    </section>\n',
    '\n',
    '    <!-- 商道 -->\n',
    '    <section id="shangdao">\n',
    '        <h2>商道</h2>\n',
    '        <p class="section-intro">侨商文化、经贸交流、诚信立业，传承商道精神</p>\n',
    '        \n',
    '        <div class="products-grid">\n',
    '            <div class="product-card">\n',
    '                <div class="icon">📊</div>\n',
    '                <h4>侨商案例</h4>\n',
    '                <p>精选东南亚成功侨商创业案例，从白手起家到商业帝国的励志故事与经验总结。</p>\n',
    '            </div>\n',
    '            <div class="product-card">\n',
    '                <div class="icon">🤝</div>\n',
    '                <h4>经贸合作</h4>\n',
    '                <p>中东南亚双边经贸合作项目撮合，提供市场对接、商务洽谈、政策咨询一站式服务。</p>\n',
    '            </div>\n',
    '            <div class="product-card">\n',
    '                <div class="icon">💼</div>\n',
    '                <h4>商务服务</h4>\n',
    '                <p>涵盖工商注册、税务规划、法律合规、人才引进等全链条企业服务体系。</p>\n',
    '            </div>\n',
    '            <div class="product-card">\n',
    '                <div class="icon">🌟</div>\n',
    '                <h4>创业经验</h4>\n',
    '                <p>定期举办创业沙龙与导师分享会，累计分享100+实战创业经验与避坑指南。</p>\n',
    '            </div>\n',
    '            <div class="product-card">\n',
    '                <div class="icon">🏪</div>\n',
    '                <h4>行业交流</h4>\n',
    '                <p>按行业细分的交流合作平台，促进产业链上下游资源对接与信息共享。</p>\n',
    '            </div>\n',
    '        </div>\n',
    '    </section>\n',
    '\n',
    '    <!-- 匠心造 -->\n',
    '    <section id="jiangxinzao">\n',
    '        <h2>匠心造</h2>\n',
    '        <p class="section-intro">用心打造精品课程、文创产品、研学项目，传递匠心精神</p>\n',
    '        \n',
    '        <div class="course-categories">\n',
    '            <div class="course-category">\n',
    '                <div class="icon">🎓</div>\n',
    '                <h4>精品课程</h4>\n',
    '                <p>系统化的教学课程体系，从入门到精通，由资深教师团队精心打磨每个教学环节。</p>\n',
    '            </div>\n',
    '            <div class="course-category">\n',
    '                <div class="icon">🎨</div>\n',
    '                <h4>文创产品</h4>\n',
    '                <p>融合传统文化元素与现代设计理念的文创衍生品，让文化触手可及。已推出茶具、文具、服饰等系列产品。</p>\n',
    '            </div>\n',
    '            <div class="course-category">\n',
    '                <div class="icon">🗺️</div>\n',
    '                <h4>研学项目</h4>\n',
    '                <p>深度文化体验研学之旅，涵盖中国各地文化名胜，结合实地探访与文化课堂。每季度推出不同主题线路。</p>\n',
    '            </div>\n',
    '            <div class="course-category">\n',
    '                <div class="icon">👥</div>\n',
    '                <h4>匠心团队</h4>\n',
    '                <p>由资深教育专家、文化学者和语言教师组成的专业教研团队，确保课程品质与教学创新。</p>\n',
    '            </div>\n',
    '            <div class="course-category">\n',
    '                <div class="icon">📜</div>\n',
    '                <h4>成果作品</h4>\n',
    '                <p>展示学员学习成果与师生共创作品，包括书法、绘画、作文、演讲视频等精彩集锦。</p>\n',
    '            </div>\n',
    '        </div>\n',
    '    </section>\n',
    '\n',
    '    <!-- 新·中国 -->\n',
    '    <section id="xinqiao">\n',
    '        <h2>新·中国</h2>\n',
    '        <p class="section-intro">新时代中国风貌、文化自信，展现当代中国的新面貌</p>\n',
    '        \n',
    '        <div class="achievements-grid">\n',
    '            <div class="achievement-item">\n',
    '                <div class="achievement-number">🌅</div>\n',
    '                <h4>新时代文化</h4>\n',
    '                <p>展现中国特色社会主义文化的繁荣发展与创新成果</p>\n',
    '            </div>\n',
    '            <div class="achievement-item">\n',
    '                <div class="achievement-number">🏛️</div>\n',
    '                <h4>国情展示</h4>\n',
    '                <p>深入了解当代中国政治、经济、社会的多元化面貌</p>\n',
    '            </div>\n',
    '            <div class="achievement-item">\n',
    '                <div class="achievement-number">🎓</div>\n',
    '                <h4>青年视角</h4>\n',
    '                <p>新时代青年的思想火花与文化担当，展现青春力量</p>\n',
    '            </div>\n',
    '            <div class="achievement-item">\n',
    '                <div class="achievement-number">🏆</div>\n',
    '                <h4>中国成就</h4>\n',
    '                <p>科技、教育、体育等领域的突破性进展与国际认可</p>\n',
    '            </div>\n',
    '            <div class="achievement-item">\n',
    '                <div class="achievement-number">🌸</div>\n',
    '                <h4>文化新貌</h4>\n',
    '                <p>传统文化与现代文明的碰撞交融，绽放新时代光彩</p>\n',
    '            </div>\n',
    '        </div>\n',
    '    </section>\n',
    '\n',
    '    <!-- 联系我们 -->\n',
    '    <section id="contact">\n',
    '        <h2>联系我们</h2>\n',
    '        <p class="section-intro">期待与您建立联系，共同探讨文化传承与商业合作的可能</p>\n',
    '        \n',
    '        <div class="contact-grid">\n',
    '            <div class="contact-card">\n',
    '                <div class="icon">📧</div>\n',
    '                <h4>邮件联系</h4>\n',
    '                <p class="contact-detail">hello@xinqiao.com</p>\n',
    '                <p>我们将尽快回复您的邮件</p>\n',
    '            </div>\n',
    '            <div class="contact-card">\n',
    '                <div class="icon">📞</div>\n',
    '                <h4>电话咨询</h4>\n',
    '                <p class="contact-detail">+86 123 4567 8900</p>\n',
    '                <p>工作日 9:00 - 18:00</p>\n',
    '            </div>\n',
    '            <div class="contact-card">\n',
    '                <div class="icon">📍</div>\n',
    '                <h4>地址</h4>\n',
    '                <p class="contact-detail">东南亚·核心城市</p>\n',
    '                <p>欢迎预约来访</p>\n',
    '            </div>\n',
    '        </div>\n',
    '    </section>\n',
    '\n',
    '    <!-- 页脚 -->\n',
    '    <footer>\n',
    '        <div class="flag-bar"></div>\n',
    '        <p>© 2024 心侨 Xinqiao - 连接心与侨的桥梁</p>\n',
    '        <p>Connecting Hearts Across Borders</p>\n',
    '    </footer>\n',
    '\n',
    '</body>\n',
    '</html>\n',
]

# Write the complete file
with open('/Users/qweqwe/Desktop/project/index.html', 'w', encoding='utf-8') as f:
    f.writelines(header_lines + new_content)

print(f"Header lines: {len(header_lines)}")
print(f"New content lines: {len(new_content)}")
print(f"Total lines: {len(header_lines) + len(new_content)}")
print("Done!")
